modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="create_automated_blase_cakes"
version="1.7.0"
displayName="Create: Automated Blase Cakes"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Robo_dude999999, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.create_automated_blase_cakes]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration